on: [puname: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      - name: Push to Git
        run: |
          mv main.pdf Cookbook.pdf
          git add Cookbook.pdf
          git commit -m "Update PDF"
          git push
